FROM node:17-alpine3.12 AS frontBuild
WORKDIR /src

RUN apk update && apk add build-base dumb-init curl tar gettext
RUN curl -L "https://github.com/PSW-Organization-8/pharmacy-front/archive/refs/heads/develop.tar.gz" | tar -xz && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" app && \
cd app && \
cd pharmacy-app && \
npm install
COPY ./environment.ts.template ./app/pharmacy-app
RUN cd app/pharmacy-app || exit && \
export API_HOST="http://localhost:8080/api/" && \
envsubst < environment.ts.template > ./src/environments/environment.ts || exit && \
npm run build --prod && \
cd dist && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" /app

FROM nginx:1.19.8-alpine AS gatewayWithFront
COPY --from=frontBuild /app /usr/share/nginx/html/app
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./api_gateway.conf /etc/nginx/api_gateway.conf
