FROM node:17-alpine3.12 AS frontBuildPatient
WORKDIR /src

RUN apk update && apk add build-base dumb-init curl tar gettext
RUN curl -L "https://github.com/PSW-Organization-8/patients-portal-front/archive/refs/heads/develop.tar.gz" | tar -xz && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" patients-portal && \
cd patients-portal && \
cd patient-application && \
#needed, otherwise npm install fails
npm config set legacy-peer-deps true && \ 
npm install
COPY ./environment.ts.template ./patients-portal/patient-application
RUN cd patients-portal/patient-application || exit && \
export API_HOST="http://localhost:5111/api/" && \
envsubst < environment.ts.template > ./src/environments/environment.prod.ts || exit && \
cat ./src/environments/environment.ts && \
#needed, otherwise build fails
export NODE_OPTIONS=--openssl-legacy-provider && \
npm run build && \
cd dist && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" /patients-portal


FROM node:17-alpine3.12 AS frontBuildPharmacy
WORKDIR /src

RUN apk update && apk add build-base dumb-init curl tar gettext
RUN curl -L "https://github.com/PSW-Organization-8/pharmacy-front/archive/refs/heads/develop.tar.gz" | tar -xz && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" pharmacy && \
cd pharmacy && \
cd pharmacy-app && \
npm install
COPY ./environment.ts.template ./pharmacy/pharmacy-app
RUN cd pharmacy/pharmacy-app || exit && \
export API_HOST="http://localhost:8080/api/" && \
envsubst < environment.ts.template > ./src/environments/environment.prod.ts || exit && \
npm run build -- --base-href='/pharmacy-front/' && \
cd dist && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" /pharmacy


FROM nginx:1.19.8-alpine AS gatewayWithFront
COPY --from=frontBuildPatient /patients-portal /usr/share/nginx/html/patients-portal
COPY --from=frontBuildPharmacy /pharmacy /usr/share/nginx/html/pharmacy
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./api_gateway.conf /etc/nginx/api_gateway.conf
