FROM node:17-alpine3.12 AS frontBuild
WORKDIR /src

RUN apk update && apk add build-base dumb-init curl tar gettext
RUN curl -L "https://github.com/PSW-Organization-8/pharmacy-front/archive/refs/heads/develop.tar.gz" | tar -xz && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" app && \
cd app && \
cd pharmacy-app && \
npm install
COPY ./environment.ts.template ./app/pharmacy-app
RUN cd app/pharmacy-app || exit && \
export API_HOST="http://localhost:8080/api/" && \
envsubst < environment.ts.template > ./src/environments/environment.ts || exit && \
npm run build --prod && \
cd dist && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" /app

FROM node:17-alpine3.12 AS frontBuildPatient
WORKDIR /src

RUN apk update && apk add build-base dumb-init curl tar gettext
RUN curl -L "https://github.com/PSW-Organization-8/patients-portal-front/archive/refs/heads/develop.tar.gz" | tar -xz && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" patients && \
cd patients && \
cd patient-application && \
npm config set legacy-peer-deps true && \ 
#needed, otherwise npm install fails
npm install
COPY ./environment.ts.template ./patients/patient-application
RUN cd patients/patient-application || exit && \
export NODE_OPTIONS=--openssl-legacy-provider && \
export API_HOST="http://localhost:5111/api/" && \
envsubst < environment.ts.template > ./src/environments/environment.ts || exit && \
npm run build --prod && \
cd dist && \
mv "$(find . -maxdepth 1 -type d | tail -n 1)" /patients

FROM nginx:1.19.8-alpine AS gatewayWithFront
COPY --from=frontBuild /app /usr/share/nginx/html/app
COPY --from=frontBuildPatient /patients /usr/share/nginx/html/patients
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./api_gateway.conf /etc/nginx/api_gateway.conf
