name: PR Validity Check
on:
  pull_request:
    branches: [develop]


jobs:
    Check-Not-At-Sprint-End:
      runs-on: ubuntu-latest
      steps:
        - name: Check if DevOps
          id: devops
          if: github.actor == 'vladimirr9' || github.actor == 'tara-pogancev' || github.actor == 'djordjekrsmanovic' || github.actor == 'zarkoblagojevic00'
          run: echo "::set-output name=devops::true"
        - name: Get current month
          id: month
          run: echo "::set-output name=month::$(date +'%m')"
        - name: Get current day
          id: day
          run: echo "::set-output name=day::$(date +'%d')"

        - name: Sprint 2 No PR period
          if: (steps.month.outputs.month == 11 && (steps.day.outputs.day == 23 || steps.day.outputs.day == 24)) && (steps.devops.outputs.devops != 'true')
          run: exit 1
        - name: Sprint 3 No PR period
          if: (steps.month.outputs.month == 12 && (steps.day.outputs.day == 11 || steps.day.outputs.day == 12)) && (steps.devops.outputs.devops != 'true')
          run: exit 1
        - name: Sprint 4 No PR period
          if: (steps.month.outputs.month == 12 && (steps.day.outputs.day == 30 || steps.day.outputs.day == 31)) && (steps.devops.outputs.devops != 'true')
          run: exit 1
        - name: Sprint 5 No PR period
          if: (steps.month.outputs.month == 1 && (steps.day.outputs.day == 22 || steps.day.outputs.day == 23)) && (steps.devops.outputs.devops != 'true')
          run: exit 1
        

